project:
  type: website
  output-dir: .

website:
  title: "NCBI viral genomes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: jumbophages.qmd
        text: Jumbo Phages
      - href: genome_size.qmd
        text: Genome size 

  page-footer:
    left: |
      Site developed by Johan S. Saenz

format:
  html:
    theme: sketchy
    css: style.css
    toc: true
