project:
  type: website
  output-dir: docs

website:
  title: "NCBI viral genomes"
  navbar:
    left:
      - href: jumbophages.qmd
        text: Jumbo Phages
      - href: genome_size.qmd
        text: Genome size 
      - href: type_molecule.qmd
        text: Molecule type
      - href: host.qmd
        text: Host

  page-footer:
    left: |
      Site [developed](https://github.com/SebasSaenz/Genbank_viral) 
      by [Johan S. Saenz](https://sebassaenz.github.io/website/)

format:
  html:
    theme: sketchy
    css: style.css
    toc: true
