project:
  type: website
  output-dir: docs

website:
  title: "NCBI viral genomes"
  twitter-card: true
  navbar:
    left:
      - href: jumbophages.qmd
        text: Jumbo Phages
      - href: genome_size.qmd
        text: Genome size 
      - href: type_molecule.qmd
        text: Molecule type
      - href: host.qmd
        text: Host
    tools:
      - icon: twitter
        href: https://twitter.com/SaenzJohanS
        text: Quarto Twitter

  page-footer:
    left: |
      Site [developed](https://github.com/SebasSaenz/Genbank_viral) 
      by [Johan S. Saenz](https://sebassaenz.github.io/website/)

format:
  html:
    theme: minty
    css: style.css
    toc: true
