project:
  type: website

website:
  title: "NCBI viral genomes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: jumbophages.qmd
        text: Jumbo Phages

  page-footer:
    left: |
      Site developed by Johan S. Saenz
