---
title: "Jumbo Phages"
date: 2024-03-30
format:
    html:
        code-fold: true
        code-summary: "Show the code"
        highlight-style: github
        code-block-border-left: true
        code-copy: true
---
# Bacteriophage host

```{r echo=FALSE, message=FALSE}
library(tidyverse)

df <- read_tsv("rawdata/clean_genomes_data.tsv") %>%
    select(host) %>%
    count(host)

total_host <- count(df) - 1
myco <- df[df$host == "Mycobacterium", "n"]
esche <- df[df$host == "Escherichia", "n"]
pseudo <- df[df$host == "Pseudomonas", "n"]
salmo <- df[df$host == "Salmonella", "n"]
unspe <- df[df$host == "Unspecified", "n"]
```

::: {.justify}
Bacteriophages in the NCBI are associated with `r total_host` different hosts. Most of the bacteriophages are linked to *Mycobacterium* (`r myco`), followed by *Escherichia* (`r esche`), *Pseudomonas* (`r pseudo`) and *Salmonella* (`r salmo`). Additionally, for a big portion of the phages (`r unspe`) the host is unknowm.
:::

<br>

```{r message=FALSE}
#| fig-width: 10
#| fig-height: 10
library(tidyverse)


df <- read_tsv("rawdata/clean_genomes_data.tsv") %>%
    select(host) %>%
    count(host) %>%
    filter(n > 100) %>%
    arrange(n) %>%
    mutate(host = factor(host, host))

df %>%
    ggplot(aes(
        x = n,
        y = host
    )) +
    geom_segment(
        aes(
            x = 0,
            xend = n,
            y = host,
            yend = host
        ),
        color = ifelse(df$host %in% "Mycobacterium", "orange", "black"),
        linewidth = ifelse(df$host %in% "Mycobacterium", 1.3, 0.7)
    ) +
    geom_point(
        size = 3,
        color = ifelse(df$host %in% "Mycobacterium", "orange", "black")
    ) +
    scale_x_continuous(
        expand = c(0, 0),
        limits = c(0, 3400),
        breaks = seq(0, 3300, 300)
    ) +
    labs(
        x = "Number of bacteriophages",
        y = "Bacteriophage host"
    ) +
    theme(
        axis.text.y = element_text(
            size = 12,
            face = "italic"
        ),
        axis.text.x = element_text(size = 15),
        axis.title.x = element_text(
            size = 20,
            face = "bold"
        ),
        axis.title.y = element_text(
            size = 20,
            face = "bold"
        ),
        panel.background = element_blank(),
        panel.grid.minor = element_line(
            color = "grey",
            linetype = 2
        ),
        legend.position = "none"
    )
```