---
title: "Jumbo Phages"
date: 2022-09-12
format:
    html:
        code-fold: true
        code-summary: "Show the code"
        highlight-style: github
        code-block-border-left: true
        code-copy: true

---

# Jumbophage genomes

```{r message=FALSE}
#| echo: false
library(tidyverse)

total <- read_tsv("rawdata/clean_genomes_data.tsv") %>%
    count()

total_jumbo <- read_tsv("rawdata/clean_genomes_data.tsv") %>%
    filter(jumbophage == TRUE) %>%
    count()

perce_jumbo <- round(100 * (total_jumbo / total), 2)
```
<br>

::: {.justify}
Tailed phages with genomes larger than 200 kbp are classified as jumbo phages. Currently there are **`r total`** bacteriophage genomes in the NCBI and only **`r perce_jumbo`%** of them are are classified as jumbo phages.
:::

<br>

```{r message=FALSE }
#| fig-width: 5
#| fig-heigth: 7
#| fig-align: center

library(tidyverse)

base_color <- c("#d8b365", "#5ab4ac")

read_tsv("rawdata/clean_genomes_data.tsv") %>%
    select(jumbophage) %>%
    count(jumbophage) %>%
    mutate(jumbophage = if_else(jumbophage == FALSE, "No Jumbo Phage",
        "Jumbo Phage"
    )) %>%
    ggplot(aes(
        x = jumbophage,
        y = n,
        fill = jumbophage
    )) +
    geom_col() +
    scale_y_continuous(
        expand = c(0, 0),
        limits = c(0, 30000),
        breaks = seq(0, 300000, 3000)
    ) +
    geom_text(
        aes(
            x = jumbophage,
            y = (n + 1500),
            label = n
        ),
        size = 6
    ) +
    labs(
        x = NULL,
        y = "Number of phages"
    ) +
    scale_fill_manual(values = base_color) +
    theme(
        text = element_text(size = 20),
        panel.background = element_blank(),
        panel.border = element_rect(
            colour = "black", fill = NA, linewidth = 1
        ),
        legend.position = "none"
    )


```